### ISSUE TITLE
Make conversion between OST and BT exact

### ISSUE THREAD

**Issue by benjaminbollen** [OpenSTFoundation/mosaic-contracts#112] opened 2018-02-23 08:22 UTC
The possible rounding error on converting OST to and fro BT is negligible given the 18 decimal fixed point precision for all sensible conversion rates.  Nonetheless we have uint256 precision to represent OST and BT; with a maximum of 800.000.000 OST, this leaves 166 bits of dynamic range to increase the fixed point precision of BT (review math: 2^90 > 10^27).  As such we should make use of those bits to remove the edge-case when further sharding $OST into $BT.

**Comment by achirala** [comment] 2018-10-05 12:30
Closing this issue because the problem is being addressed elsewhere.

**Closed** 2018-10-05 12:29 UTC

**Comment by schemar** [comment] 2018-10-05 16:01
@achirala where specifically?
